<a href="https://colab.research.google.com/github/lukaszek358/Data_Science_Bootcamp/blob/main/1_Data_Science_Bootcamp_w_j%C4%99zyku_Python_od_A_do_Z_Numpy_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Podstawy

In [3]:
#import biblioteki
import numpy as np
np.__version__

'1.22.4'

In [ ]:
#klasy/ metody/ atrybuty biblioteki numpy
print(dir(np))

In [ ]:
# wyświetlanie pomocy do określonej metody w biblioteki

help(np.array)

## 1D Array (tablica 1-wymiarowa [One-Dimension Array])

In [7]:
x = np.array([1, 3])
x

array([1, 3])

In [10]:
print(x)
print(type(x))

[1 3]
<class 'numpy.ndarray'>


In [12]:
#liczba wymiarów
x.ndim

1

In [14]:
x.shape #kształt

(2,)

In [15]:
x.size #liczba elementów

2

In [16]:
x.dtype #typ danych

dtype('int64')

In [19]:
x = np.array([1.3, 2.3, 1.4])
print(x)

[1.3 2.3 1.4]


In [20]:
x.dtype

dtype('float64')

##2D Array

In [22]:
x = np.array([[1, 2], [-3, 1]])

In [23]:
x.ndim #liczba wymiarów

2

In [24]:
x.shape #wielkosć tablicy (kształt)

(2, 2)

In [25]:
x.size # liczba elementów

4

In [26]:
x = np.array([[1, 2, 4], [4, 2, 1]])
print(x)

[[1 2 4]
 [4 2 1]]


In [27]:
x.shape

(2, 3)

##3D Array

In [28]:
x = np.array(
    [[[4, 3, 1],
      [3, 1, 2]],
     [[4, 1, 3],
      [4, 2, 1]]]
)
x

array([[[1, 2, 4],
        [4, 2, 1]],

       [[4, 1, 3],
        [4, 2, 1]]])

In [31]:
x.ndim

3

In [36]:
print(f' 2 elementy - 2 wiersze - 3 kolumny: \n{x.shape}')

 2 elementy - 2 wiersze - 3 kolumny: 
(3, 2, 3)


In [37]:
x = np.array(
    [[[4, 3, 1],
      [3, 1, 2]],
     [[4, 1, 3],
      [4, 2, 1]],
     [[3, 2, 1],
      [4, 3, 2]]]
)
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]],

       [[3, 2, 1],
        [4, 3, 2]]])

In [42]:
print(f' 3 elementy - 2 wiersze - 3 kolumny:\t{x.shape}')

 3 elementy - 2 wiersze - 3 kolumny:	(3, 2, 3)


In [40]:
x.ndim #liczba wymiarów

3